Backend endpoint recents
broxburyTechtonic/techtonic_slack_shoutout_bot pull request #26
Opened 2020-10-23 16:28 UTC by emackinnonTechtonic

### Type of change:
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Styling - no new features

### Why is this change required? What problem(s) does it solve?
On this PR I have broken out the routes and controllers into their own separate folders. The recent shouts endpoint is created to pull in the necessary data to the landing page's Carousel component.
### Were there any challenges while implementing this feature? If so, how were they addressed?
N/A
### Where should the reviewer start? How can this be tested?
We plan on making documentation to get the app running on a local machine.
### Link issues
#7

2020-10-23 17:58 UTC, tgeeTechtonic commented on server/controllers/shoutoutController.js
> +const db = require('knex')(config);
I think that these should probably stay in App and then you can just import `db` into the controller

2020-10-23 17:59 UTC, tgeeTechtonic commented on server/package.json
> +    "nodemon": "^2.0.6",
Should probably change this to a dev dependency and also add a dev start script as well

2020-10-23 18:00 UTC, tgeeTechtonic requested changes
I think we should reorganize a few things before merging this into develop, but otherwise, this looks great!

2020-10-26 21:10 UTC, broxburyTechtonic approved these changes

2020-10-26 21:11 UTC, tgeeTechtonic approved these changes
Looks good now!

2020-10-26 21:11 UTC, merged